version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - java -version
      #- mvn install
      - mvn test -Dcloud.aws.credentials.accessKey=a -D cloud.aws.credentials.secretKey=a
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar