version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - java -version
      #- mvn install
      - mvn test -Dcloud.aws.credentials.accessKey=a -D cloud.aws.credentials.secretKey=a -Dapp.bucket_name=a
      - mvn package -DskipTests
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  > imageDetail.json
      - sed -i 's/<APP_NAME>/'$IMAGE_REPO_NAME'/g' appspec.yml taskdef.json
      - sed -i 's/<SERVICE_PORT>/'$SERVICE_PORT'/g' appspec.yml taskdef.json
      - sed -i 's/<AWS_ACCOUNT_ID>/'$AWS_ACCOUNT_ID'/g' taskdef.json
      - sed -i 's/<MEMORY_RESV>/'$MEMORY_RESV'/g' taskdef.json
      - sed -i 's/<IMAGE_NAME>/'$AWS_ACCOUNT_ID'\.dkr\.ecr\.'$AWS_DEFAULT_REGION'\.amazonaws.com\/'$IMAGE_REPO_NAME'\:'$IMAGE_TAG'/g' taskdef.json
      - sed -i 's/<APP_BUCKET_NAME>/'$APP_BUCKET_NAME'/g' taskdef.json
      # arns have slashes, sed command needs to be adjusted
      - sed -i 's|<AWS_ACCESS_KEY_ID_ARN>|'$AWS_ACCESS_KEY_ID_ARN'|g' taskdef.json
      - sed -i 's|<AWS_SECRET_ACCESS_KEY_ARN>|'$AWS_SECRET_ACCESS_KEY_ARN'|g' taskdef.json
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - taskdef.json
    - imageDetail.json